language: cpp

compiler:
  - g++

before_install:
  - git clone https://github.com/IWillFindYou/SecurityBootManager-Example examples
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential flex bison texinfo autoconf automake gettext

script: ./.travis.sh

